---

 - name: adding credentials to root account
   lineinfile: create=yes dest=/root/.boto insertafter=EOF line="{{ item }}" owner=root group=root
   with_items:
   - '[Credentials]'
   - 'aws_access_key_id="{{ aws_key}}"'
   - 'aws_secret_access_key="{{ aws_secret }}"'

 - name: 'Cd and run'
   sudo: true
   shell: "cd /home/ubuntu/crabot/bot; python main.py"
